# Generated by Django 5.0.1 on 2024-03-08 05:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name', max_length=25)),
                ('last_name', models.CharField(default='Last Name', max_length=25)),
                ('ssn', models.CharField(default=-1011, max_length=11)),
                ('customer_since', models.DateField(default=datetime.date(2024, 3, 8))),
                ('preferred_customer', models.CharField(max_length=1)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['ssn'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=11111)),
                ('account_type', models.CharField(max_length=1)),
                ('balance', models.FloatField(default=2)),
                ('agreement', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='CustAcctMgmtApp.customer')),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=1)),
                ('transaction_amount', models.FloatField(default=2)),
                ('initiated_date', models.DateField(default=datetime.date(2024, 3, 8))),
                ('posted_date', models.DateField(default=datetime.date(2024, 3, 8))),
                ('status', models.CharField(max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CustAcctMgmtApp.account')),
            ],
            options={
                'ordering': ['transaction_type'],
            },
        ),
    ]
