# Generated by Django 5.0.1 on 2024-03-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_type']},
        ),
    ]
