# Generated by Django 5.0.1 on 2024-03-12 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='agreement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.date(2024, 3, 12)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_date',
            field=models.DateField(default=datetime.date(2024, 3, 12)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 3, 12)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
    ]
