# Generated by Django 5.0.1 on 2024-03-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0003_alter_account_account_number_alter_account_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ssn',
            field=models.CharField(default='111-11-1111', max_length=11),
        ),
    ]
