# Generated by Django 5.0.1 on 2024-03-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0004_alter_customer_ssn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_number']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['account_id']},
        ),
    ]
