# Generated by Django 5.0.1 on 2024-03-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0005_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paper_statement',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
