# Generated by Django 5.0.1 on 2024-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0006_account_paper_statement_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paper_statement',
            field=models.BooleanField(default=False),
        ),
    ]
