# Generated by Django 5.0.1 on 2024-03-13 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0007_alter_account_paper_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_date',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
    ]
