# Generated by Django 5.0.1 on 2024-03-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0008_alter_account_password_alter_customer_customer_since_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_amount',
        ),
    ]
