# Generated by Django 5.0.1 on 2024-03-14 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustAcctMgmtApp', '0009_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.date(2024, 3, 14)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_date',
            field=models.DateField(default=datetime.date(2024, 3, 14)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='posted_date',
            field=models.DateField(default=datetime.date(2024, 3, 14)),
        ),
    ]
